name: Lint (develop targeted PR)

on:
  pull_request:
    branches: ["develop"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |-
          yarn && yarn lint
